<?php

namespace AppBundle\Repository;

/**
 * ApiGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApiGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
